[package]
name = "imxrt-fcb-gen"
version = "0.1.0"
authors = ["Ian McIntyre <ianpmcintyre@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/imxrt-rs/imxrt-fcb-gen"
description = """
Generate Firmware Configuration Block (FCB) for iMXRT processors in Rust build scripts.
"""
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
keywords = [
    "arm",
    "cortex-m",
    "imxrt",
]

[dependencies]

[features]
imxrt1011 = []
imxrt1061 = []
imxrt1062 = []
imxrt1064 = []

[package.metadata.docs.rs]
features = ["imxrt1062"]