name: All Checks

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        feature: ["imxrt1010", "imxrt1060", "imxrt1064"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build (${{ matrix.feature }})
      run: cargo build --verbose --features ${{ matrix.feature }}
    - name: Run tests (${{ matrix.feature }})
      run: cargo test --verbose --features ${{ matrix.feature }}
  
  clippy:
    strategy:
      matrix:
        feature: ["imxrt1010", "imxrt1060"]
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features ${{ matrix.feature }} -- -D warnings
          name: Run clippy (${{ matrix.feature }})

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
